# fastq_folder: '/home/alfred/other_people/bnsengim/np_amp_clair3_demo_07-07-25/fastq'
genome_fasta: '/home/charlie/data/gatk4-illumina_test_data/genome/PlasmoDB-62_Pfalciparum3D7_Genome.fasta'
genome_gff: '/home/charlie/data/gatk4-illumina_test_data/genome/PlasmoDB-62_Pfalciparum3D7.gff'
output_folder: 'results'
model_path: '/home/alfred/micromamba/envs/clair3/bin/models/r1041_e82_400bps_sup_v410'
snp_eff_folder: '.pixi/envs/default/share/snpeff-5.4.0a-0'
targets_tsv: 'config/targets.tsv'

#name and description of a snpEff database to be built
genome_database_name: 'plasmoDB_3D7_v62'
database_description: 'A database for plasmoDB version 62'

#filtering settings for clair3 - leave these alone for now
snp_min_af: 0.000
indel_min_af: 0.000
