# Path to the genome and gff files
# ------------------------------------------------------------------------------------
genome_fasta: resources/PlasmoDB-62_Pfalciparum3D7_Genome.fasta
genome_gff: resources/PlasmoDB-62_Pfalciparum3D7.gff

# vcf file of variant called reads performed by either clair3 or gatk
# -----------------------------------------------------------------------------------
merged_vcf: resources/genotyped_cohort.vcf.gz

#name and description of a snpEff database to be built
# ------------------------------------------------------------------------------------
genome_database_name: "plasmoDB_3D7_v62"
database_description: "A database for plasmoDB version 62"

# targets.tsv file containing mutations of particular interest
# see the example in the config file for formatting requirements
# ------------------------------------------------------------------------------------
targets_tsv: "config/targets.tsv"

# Output folder where the results will go
# ------------------------------------------------------------------------------------
output_directory: "results"
